apiVersion: v1
kind: ConfigMap
metadata:
  name: recyclarr-config
  namespace: default
data:
  recyclarr.yml: |
    radarr:
      movies:
        base_url: http://radarr.default.svc.cluster.local:7878
        api_key: !env RADARR_API_KEY
        include:
          - template: radarr-quality-definition-movie
          - template: radarr-custom-formats-hd-bluray-web

    sonarr:
      tv:
        base_url: http://sonarr.default.svc.cluster.local:8989
        api_key: !env SONARR_API_KEY
        include:
          - template: sonarr-quality-definition-series
          - template: sonarr-custom-formats-web-1080p
