apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
data:
  settings.yaml: |
    title: Home Dashboard
    theme: dark
  services.yaml: |
    - Infrastructure:
        - Glances:
            icon: glances.png
            href: http://glances.thuis
            description: System Monitoring
  widgets.yaml: |
    - logo:
        icon: https://gethomepage.dev/img/homepage-logo.png
