controllers:
  main:
    containers:
      main:
        image:
          repository: lscr.io/linuxserver/radarr
          tag: latest
        env:
          TZ: Europe/Amsterdam
          PUID: "1000"
          PGID: "100"

service:
  main:
    controller: main
    ports:
      http:
        port: 7878

ingress:
  main:
    enabled: true
    className: traefik
    hosts:
      - host: radarr.thuis
        paths:
          - path: /
            service:
              identifier: main
              port: http

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    storageClass: local-path
    accessMode: ReadWriteOnce
    size: 2Gi
    globalMounts:
      - path: /config
  data:
    enabled: true
    type: hostPath
    hostPath: /data
    globalMounts:
      - path: /data
